In [1]:
import os

current_directory = os.getcwd()
print("Current Working Directory:", current_directory)

to_dir = current_directory + "/.."
os.chdir(to_dir)
current_directory = os.getcwd()
print("Changed Working Directory:", current_directory)


Current Working Directory: E:\my_project\PycharmProjects\connect-four-rl\quick_trial
Changed Working Directory: E:\my_project\PycharmProjects\connect-four-rl


In [2]:
from game_env.GameEngine import GameEngine

In [3]:
engine = GameEngine()

In [4]:
board = engine.create_board()

In [8]:
board[0,0] = 1
board[0,1] = 2
board[0,2] = 1
board[0,3] = 1
board[1,3] = 2
board



array([[1., 2., 1., 1., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
board == 1

array([[ True, False,  True,  True, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [10]:
board == 2

array([[False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [17]:
import numpy as np
board2 = np.zeros((2,GameEngine.ROW_COUNT, GameEngine.COLUMN_COUNT))


In [18]:
board2[0,:,:] = (board == 1)
board2[1,:,:] = (board == 2)



In [19]:
board2.shape

(2, 6, 7)

In [20]:
board2

array([[[1., 0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])